# Data Manipulation

## Background

This focuses on the analysis of historical data from the Olympic games.  The description of the data includes the following:
> This is a historical dataset on the modern Olympic Games, including all the Games from Athens 1896 to Rio 2016. I scraped this data from www.sports-reference.com in May 2018.

## 0. Download the data from: 
- https://www.kaggle.com/heesoo37/120-years-of-olympic-history-athletes-and-results
- https://en.wikipedia.org/wiki/List_of_Olympic_Games_host_cities (note: we suggest you use the [read_html](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_html.html) function to load the data into a DataFrame.

## 1. Answer the questions below. 
For each question, you should
1. Write code using Python and pandas that can help you answer the following questions, and
2. Explain your answers in plain English. You should use complete sentences that would be understood by an educated professional who is not necessarily a data scientist (like a product manager).

### 5 pt: Describe the dataset. 
- How many number rows and columns do you see in each data frame? 
- Are there any other interesting descriptive details?

In [2]:
#! pip install --user spacy
#!pip install --upgrade pip
#!pip uninstall numpy --yes
!python3.5 -m pip install pandas
#!python3.5 -m pip install --upgrade pip
#sudo apt-get purge python3-numpy

Requirement already satisfied: pandas in /home/ketan/.local/lib/python3.5/site-packages (0.23.3)
Requirement already satisfied: pytz>=2011k in /home/ketan/.local/lib/python3.5/site-packages (from pandas) (2018.9)
Requirement already satisfied: python-dateutil>=2.5.0 in /home/ketan/.local/lib/python3.5/site-packages (from pandas) (2.7.5)
Requirement already satisfied: numpy>=1.9.0 in /home/ketan/.local/lib/python3.5/site-packages (from pandas) (1.16.0)
Requirement already satisfied: six>=1.5 in /home/ketan/.local/lib/python3.5/site-packages (from python-dateutil>=2.5.0->pandas) (1.11.0)

In [1]:
! pip install pandas

Traceback (most recent call last):
  File "/home/ketan/anaconda2/bin/pip", line 6, in <module>
    from pip._internal import main
ImportError: No module named _internal

In [31]:
# put your code here
import pandas as pd
df = pd.read_csv('athlete_events.csv', encoding = 'utf-8')
df
#print("No. of (rows, columns) is")
#print(df.shape)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
5,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
6,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,Speed Skating Women's 500 metres,NaN
7,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
8,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,Speed Skating Women's 500 metres,NaN
9,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
10,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
11,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN
12,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
13,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
14,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
15,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 30 kilometres,NaN
16,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
17,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
18,7,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
19,7,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN
20,7,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
21,7,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
22,7,John Aalberg,M,33.0,183.0,72.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
23,7,John Aalberg,M,33.0,183.0,72.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 30 kilometres,NaN
24,7,John Aalberg,M,33.0,183.0,72.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
25,7,John Aalberg,M,33.0,183.0,72.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
26,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN
27,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 4 x 100 metres Relay,NaN
28,9,Antti Sami Aalto,M,26.0,186.0,96.0,Finland,FIN,2002 Winter,2002,Winter,Salt Lake City,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
29,10,"Einar Ferdinand ""Einari"" Aalto",M,26.0,NaN,NaN,Finland,FIN,1952 Summer,1952,Summer,Helsinki,Swimming,Swimming Men's 400 metres Freestyle,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271086,135555,Micha Zych,M,23.0,177.0,68.0,Poland,POL,2006 Winter,2006,Winter,Torino,Figure Skating,Figure Skating Mixed Ice Dancing,NaN
271087,135556,Bogusaw Stanisaw Zychowicz,M,19.0,189.0,80.0,Poland,POL,1980 Summer,1980,Summer,Moskva,Swimming,Swimming Men's 100 metres Butterfly,NaN
271088,135556,Bogusaw Stanisaw Zychowicz,M,19.0,189.0,80.0,Poland,POL,1980 Summer,1980,Summer,Moskva,Swimming,Swimming Men's 200 metres Butterfly,NaN
271089,135557,Dominik ycki,M,34.0,192.0,95.0,Poland,POL,2008 Summer,2008,Summer,Beijing,Sailing,Sailing Men's Two Person Keelboat,NaN
271090,135557,Dominik ycki,M,38.0,192.0,95.0,Poland,POL,2012 Summer,2012,Summer,London,Sailing,Sailing Men's Two Person Keelboat,NaN
271091,135558,ukasz Tomasz ygado,M,32.0,200.0,89.0,Poland,POL,2012 Summer,2012,Summer,London,Volleyball,Volleyball Men's Volleyball,NaN
271092,135559,Pawe Jan Zygmunt,M,21.0,182.0,79.0,Poland,POL,1994 Winter,1994,Winter,Lillehammer,Speed Skating,"Speed Skating Men's 1,500 metres",NaN
271093,135559,Pawe Jan Zygmunt,M,21.0,182.0,79.0,Poland,POL,1994 Winter,1994,Winter,Lillehammer,Speed Skating,"Speed Skating Men's 5,000 metres",NaN
271094,135559,Pawe Jan Zygmunt,M,25.0,182.0,79.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Speed Skating,"Speed Skating Men's 1,500 metres",NaN
271095,135559,Pawe Jan Zygmunt,M,25.0,182.0,79.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Speed Skating,"Speed Skating Men's 5,000 metres",NaN
271096,135559,Pawe Jan Zygmunt,M,29.0,182.0,79.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Speed Skating,"Speed Skating Men's 5,000 metres",NaN
271097,135559,Pawe Jan Zygmunt,M,29.0,182.0,79.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Speed Skating,"Speed Skating Men's 10,000 metres",NaN
271098,135559,Pawe Jan Zygmunt,M,33.0,182.0,79.0,Poland,POL,2006 Winter,2006,Winter,Torino,Speed Skating,"Speed Skating Men's 5,000 metres",NaN
271099,135560,Stavroula Zygouri,F,36.0,171.0,63.0,Greece,GRE,2004 Summer,2004,Summer,Athina,Wrestling,"Wrestling Women's Middleweight, Freestyle",NaN
271100,135561,Frantiek Zyka,M,26.0,NaN,NaN,Czechoslovakia,TCH,1928 Summer,1928,Summer,Amsterdam,Athletics,Athletics Men's Marathon,NaN
271101,135562,Milan Zyka,M,24.0,173.0,68.0,Czechoslovakia,TCH,1972 Summer,1972,Summer,Munich,Cycling,"Cycling Men's Team Pursuit, 4,000 metres",NaN
271102,135563,Olesya Nikolayevna Zykina,F,19.0,171.0,64.0,Russia,RUS,2000 Summer,2000,Summer,Sydney,Athletics,Athletics Women's 4 x 400 metres Relay,Bronze
271103,135563,Olesya Nikolayevna Zykina,F,23.0,171.0,64.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Athletics,Athletics Women's 4 x 400 metres Relay,Silver
271104,135564,Yevgeny Aleksandrovich Zykov,M,22.0,172.0,65.0,Russia-1,RUS,2002 Winter,2002,Winter,Salt Lake City,Luge,Luge Mixed (Men)'s Doubles,NaN
271105,135565,Fernando scar Zylberberg,M,23.0,168.0,76.0,Argentina,ARG,2000 Summer,2000,Summer,Sydney,Hockey,Hockey Men's Hockey,NaN
271106,135565,Fernando scar Zylberberg,M,27.0,168.0,76.0,Argentina,ARG,2004 Summer,2004,Summer,Athina,Hockey,Hockey Men's Hockey,NaN
271107,135566,"James Francis ""Jim"" Zylker",M,21.0,175.0,75.0,United States,USA,1972 Summer,1972,Summer,Munich,Football,Football Men's Football,NaN
271108,135567,Aleksandr Viktorovich Zyuzin,M,24.0,183.0,72.0,Russia,RUS,2000 Summer,2000,Summer,Sydney,Rowing,Rowing Men's Lightweight Coxless Fours,NaN
271109,135567,Aleksandr Viktorovich Zyuzin,M,28.0,183.0,72.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Rowing,Rowing Men's Lightweight Coxless Fours,NaN
271110,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016 Summer,2016,Summer,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

### 5 pt: What is the overall ratio of female to male atheletes? 
There are multiple ways one could determine the meaning of "overall" here, and there isn't necessarily one correct answer. Based on your interpretation, give a justification for the choices you made in your analysis.

In [2]:
# put your code here
from fractions import Fraction
#Masking
male_df=df.loc[df['Sex']=='M']

female_df=df.loc[df['Sex']=='F']
print ("Male Size: ", len(male_df),". Female Size: ", len(female_df))

print ("Male:Female Ratio is")
print(Fraction(len(male_df)/float(len(female_df))).limit_denominator(10))

Male Size:  196594 . Female Size:  74522
Male:Female Ratio is
21/8

### 10 pt: Which athelete competed in most number of events? 
In which events did the athelete participate, and for what range of years? Which country did the athlete represent?

In [3]:
# put your code here

#pd.Series(df["Event"].values)
#df["Year"].sort_values()
#df.groupby(['ID'])['Year'].max()
#df.groupby(['ID'])['Year'].min()
df.groupby(['ID']).agg({'Year':['min', 'max','count']})

        Year
         min   max count
ID
1       1992  1992     1
2       2012  2012     1
3       1920  1920     1
4       1900  1900     1
5       1988  1994     6
6       1992  1994     8
7       1992  1994     8
8       1932  1932     2
9       2002  2002     1
10      1952  1952     1
11      1980  1980     1
12      2000  2000     1
13      1996  2000     2
14      1994  1994     1
15      1912  1924     5
16      2014  2014     1
17      1948  1952    16
18      2000  2000     1
19      1948  1948     1
20      1992  2006    20
21      2008  2008     1
22      2016  2016     1
23      2000  2004     2
24      1960  1964     3
25      1920  1920     1
26      1984  1984     1
27      1984  1984     1
28      1968  1972     2
29      1988  1988     1
30      1996  2000     2
...      ...   ...   ...
135542  1956  1956     2
135543  1964  1964     1
135544  1980  1980     2
135545  1988  1996     3
135546  1998  1998     2
135547  2012  2016     4
135548  1972  1972     1
135549  2002  2002     5
135550  2002  2002     4
135551  1998  2002     9
135552  1928  1928     1
135553  1952  1964     5
135554  1980  1988     5
135555  2006  2006     1
135556  1980  1980     2
135557  2008  2012     2
135558  2012  2012     1
135559  1994  2006     7
135560  2004  2004     1
135561  1928  1928     1
135562  1972  1972     1
135563  2000  2004     2
135564  2002  2002     1
135565  2000  2004     2
135566  1972  1972     1
135567  2000  2004     2
135568  2016  2016     1
135569  1976  1976     1
135570  2014  2014     2
135571  1998  2002     2

[135571 rows x 3 columns]

In [4]:
df.groupby(['ID'])['Team'].apply(list)

ID
1                                                   [China]
2                                                   [China]
3                                                 [Denmark]
4                                          [Denmark/Sweden]
5         [Netherlands, Netherlands, Netherlands, Nether...
6         [United States, United States, United States, ...
7         [United States, United States, United States, ...
8                                [Netherlands, Netherlands]
9                                                 [Finland]
10                                                [Finland]
11                                                [Finland]
12                                                [Finland]
13                                       [Finland, Finland]
14                                                [Finland]
15            [Finland, Finland, Finland, Finland, Finland]
16                                                [Finland]
17        [Finland, Finland, Finland, Finland, Finland, ...
18                                                [Finland]
19                                                [Finland]
20        [Norway, Norway, Norway, Norway, Norway, Norwa...
21                                                 [Norway]
22                                                [Romania]
23                                         [Norway, Norway]
24                                 [Norway, Norway, Norway]
25                                                 [Norway]
26                                                 [Norway]
27                                            [Netherlands]
28                                         [Norway, Norway]
29                                            [Netherlands]
30                               [Netherlands, Netherlands]
                                ...
135542                           [Switzerland, Switzerland]
135543                                      [United States]
135544                                     [Poland, Poland]
135545              [Netherlands, Netherlands, Netherlands]
135546                           [Netherlands, Netherlands]
135547     [Kazakhstan, Kazakhstan, Kazakhstan, Kazakhstan]
135548                                       [Soviet Union]
135549        [Belarus, Belarus, Belarus, Belarus, Belarus]
135550                 [Belarus, Belarus, Belarus, Belarus]
135551    [Lithuania, Lithuania, Lithuania, Lithuania, L...
135552                                             [Poland]
135553    [Soviet Union, Soviet Union, Soviet Union, Sov...
135554             [Poland, Poland, Poland, Poland, Poland]
135555                                             [Poland]
135556                                     [Poland, Poland]
135557                                     [Poland, Poland]
135558                                             [Poland]
135559    [Poland, Poland, Poland, Poland, Poland, Polan...
135560                                             [Greece]
135561                                     [Czechoslovakia]
135562                                     [Czechoslovakia]
135563                                     [Russia, Russia]
135564                                           [Russia-1]
135565                               [Argentina, Argentina]
135566                                      [United States]
135567                                     [Russia, Russia]
135568                                            [Belarus]
135569                                           [Poland-1]
135570                                     [Poland, Poland]
135571                                     [Poland, Poland]
Name: Team, Length: 135571, dtype: object

### 10 pt: Which sport has the highest median athlete age? 
To determine this, you might want to plot the median age for each sport. You may want to sort the axes appropriately for your analysis.

In [5]:
# put your code here
filtered_df=df.dropna(subset=['Age'])
#df.shape,filtered_df.shape
sorted_age=filtered_df.sort_values(['Age'], ascending=[False])
sorted_age.groupby(['Games'])['Age'].median()

Games
1896 Summer    23.0
1900 Summer    27.0
1904 Summer    24.0
1906 Summer    25.0
1908 Summer    25.0
1912 Summer    25.0
1920 Summer    28.0
1924 Summer    26.0
1924 Winter    26.0
1928 Summer    26.0
1928 Winter    25.0
1932 Summer    28.0
1932 Winter    24.0
1936 Summer    26.0
1936 Winter    24.0
1948 Summer    27.0
1948 Winter    26.0
1952 Summer    25.0
1952 Winter    24.0
1956 Summer    25.0
1956 Winter    25.0
1960 Summer    24.0
1960 Winter    24.0
1964 Summer    24.0
1964 Winter    24.0
1968 Summer    23.0
1968 Winter    24.0
1972 Summer    24.0
1972 Winter    24.0
1976 Summer    23.0
1976 Winter    23.0
1980 Summer    23.0
1980 Winter    23.0
1984 Summer    23.0
1984 Winter    23.0
1988 Summer    23.0
1988 Winter    23.0
1992 Summer    24.0
1992 Winter    24.0
1994 Winter    24.0
1996 Summer    24.0
1998 Winter    25.0
2000 Summer    25.0
2002 Winter    26.0
2004 Summer    25.0
2006 Winter    25.0
2008 Summer    25.0
2010 Winter    25.0
2012 Summer    25.0
2014 Winter    26.0
2016 Summer    26.0
Name: Age, dtype: float64

### 10 pt: In which events has the Netherlands won the most medals?

In [43]:
# put your code here
neth_df=df[df['Team']=='Netherlands'].dropna(subset=['Medal'])

#neth_df
sorted_data=neth_df.groupby(['Sport'])[['Medal']].count().reset_index().sort_values(by=['Medal'], ascending=False)
print(sorted_data.iloc[0,:])

Sport    Hockey
Medal       255
Name: 12, dtype: object

### 10 pt: Which countries have more female medalists than male medalists?

In [14]:
# put your code here
#df
#df.groupby(['Team'])
male_fem_count=df.groupby(['Team','Sex']).size().sort_values(by=['Team','Sex'],ascending=False)#.reset_index()
#.sort_values(by=['0']).apply(lambda x: x['Sex'])
#male_fem_count['TotalCount']=df.groupby(['Team']).count()
male_fem_count

Team                          Sex
30. Februar                   M         2
A North American Team         M         4
Acipactli                     M         3
Acturus                       M         2
Afghanistan                   F         5
                              M       121
Akatonbo                      M         3
Alain IV                      M         3
Albania                       F        27
                              M        43
Alcaid                        M         3
Alcyon-6                      M         1
Alcyon-7                      M         2
Aldebaran                     M         2
Aldebaran II                  M         2
Aletta                        M         3
Algeria                       F        94
                              M       457
Ali-Baba II                   M         7
Ali-Baba IV                   M         2
Ali-Baba IX                   M         2
Ali-Baba VI                   M         2
Allegro                       M         3
Almaz                         M         2
Aloha II                      M         5
Amateur Athletic Association  M         5
American Samoa                F         7
                              M        30
Amolgavar                     M         3
Amstel Amsterdam              M         4
                                     ...
Whitini Star                  M         1
Widgeon                       M         2
Wiking                        M         5
Willem-Six                    M         3
Windor                        M         2
Winnipeg Shamrocks-1          M        12
Wolseley-Siddeley-1           M         4
Xantippa                      M         3
Xolotl                        M         3
Yangon                        M         2
Yemen                         F         4
                              M        28
Yeoman                        M         4
Yeoman V                      M         3
Yeoman VII                    M         3
Yeoman XII                    M         3
Ylliam II                     M         5
Ylliam VII                    M         6
Ylliam VIII                   M         5
Yugoslavia                    F       378
                              M      2180
Yugoslavia-1                  M        10
Yugoslavia-2                  M        10
Zambia                        F        19
                              M       164
Zefyros                       M         2
Zimbabwe                      F       113
                              M       196
Zut                           M         3
rn-2                          M         5
Length: 1528, dtype: int64

### 10 pt: Which country won the most medal points in each of the 2016 Summer Olympics?
Rank each country by a score, where 3 points are assigned for a gold medal, 2 points for silver, and 1 point for bronze.

In [44]:
# put your code here
medals=df.dropna(subset=['Medal'])[['Team','Medal']];
medals.loc[medals['Medal']=='Gold','Point']=3
medals.loc[medals['Medal']=='Silver','Point']=2
medals.loc[medals['Medal']=='Bronze','Point']=1
medals.groupby(['Team'])['Point'].agg('sum').reset_index().sort_values(['Point'], ascending=False).reset_index()
#df.apply(lambda x: 3 if x['Medal']=='Gold' else 2, axis=1)

     index            Team    Point
0      462   United States  11679.0
1      403    Soviet Union   5283.0
2      165         Germany   3969.0
3      171   Great Britain   3293.0
4      215           Italy   3105.0
5      149          France   2978.0
6      420          Sweden   2812.0
7       67          Canada   2500.0
8       18       Australia   2443.0
9      198         Hungary   2321.0
10     364          Russia   2193.0
11     117    East Germany   1988.0
12     304     Netherlands   1863.0
13      78           China   1842.0
14     321          Norway   1838.0
15     219           Japan   1712.0
16     145         Finland   1535.0
17     400     South Korea   1236.0
18     356         Romania   1173.0
19     105         Denmark   1112.0
20     426     Switzerland   1089.0
21     484    West Germany   1052.0
22     340          Poland    990.0
23     406           Spain    938.0
24     103  Czechoslovakia    871.0
25      99            Cuba    862.0
26     494      Yugoslavia    817.0
27      54          Brazil    816.0
28      21         Austria    771.0
29      36         Belgium    758.0
..     ...             ...      ...
468    197        Humbug V      2.0
469    107       Denmark-2      2.0
470    106       Denmark-1      2.0
471    373     Scamasaxe-2      2.0
472    178        Greece-2      2.0
473    378         Senegal      2.0
474    381        Shrew II      2.0
475    442           Tonga      2.0
476     81         China-3      2.0
477     84        Chuckles      2.0
478    180       Guatemala      2.0
479    182          Guyana      1.0
480    208            Iraq      1.0
481    450     Turquoise-1      1.0
482    290          Monaco      1.0
483    283        Mignon-3      1.0
484    278       Mauritius      1.0
485    132         Eritrea      1.0
486    146         Formosa      1.0
487    155       Frimousse      1.0
488    266       Macedonia      1.0
489    345         Potsdam      1.0
490     87      Clearwater      1.0
491    244        Laurea-1      1.0
492     31        Barbados      1.0
493    441            Togo      1.0
494    112        Djibouti      1.0
495    111           Digby      1.0
496     42         Bermuda      1.0
497    115     Don Schufro      1.0

[498 rows x 3 columns]

### 20 pt: For each year in which games were held, what proportion of gold medals did the host country win? 
You will need to combine multiple datasets to complete the analysis.

In [72]:
# put your code here

medals2=df.dropna(subset=['Medal'])
medals2['Point']=medals2.apply(lambda x: 3 if x['Medal']=='Gold' else 2 if x['Medal']=='Silver' else 1 if x['Medal']=='Bronze' else  0, axis=1)
medals2

/home/ketan/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,Point
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,3
37,15,Arvo Ossian Aaltonen,M,30.0,NaN,NaN,Finland,FIN,1920 Summer,1920,Summer,Antwerpen,Swimming,Swimming Men's 200 metres Breaststroke,Bronze,1
38,15,Arvo Ossian Aaltonen,M,30.0,NaN,NaN,Finland,FIN,1920 Summer,1920,Summer,Antwerpen,Swimming,Swimming Men's 400 metres Breaststroke,Bronze,1
40,16,Juhamatti Tapio Aaltonen,M,28.0,184.0,85.0,Finland,FIN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,1
41,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948 Summer,1948,Summer,London,Gymnastics,Gymnastics Men's Individual All-Around,Bronze,1
42,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948 Summer,1948,Summer,London,Gymnastics,Gymnastics Men's Team All-Around,Gold,3
44,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948 Summer,1948,Summer,London,Gymnastics,Gymnastics Men's Horse Vault,Gold,3
48,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948 Summer,1948,Summer,London,Gymnastics,Gymnastics Men's Pommelled Horse,Gold,3
50,17,Paavo Johannes Aaltonen,M,32.0,175.0,64.0,Finland,FIN,1952 Summer,1952,Summer,Helsinki,Gymnastics,Gymnastics Men's Team All-Around,Bronze,1
60,20,Kjetil Andr Aamodt,M,20.0,176.0,85.0,Norway,NOR,1992 Winter,1992,Winter,Albertville,Alpine Skiing,Alpine Skiing Men's Super G,Gold,3
61,20,Kjetil Andr Aamodt,M,20.0,176.0,85.0,Norway,NOR,1992 Winter,1992,Winter,Albertville,Alpine Skiing,Alpine Skiing Men's Giant Slalom,Bronze,1
63,20,Kjetil Andr Aamodt,M,22.0,176.0,85.0,Norway,NOR,1994 Winter,1994,Winter,Lillehammer,Alpine Skiing,Alpine Skiing Men's Downhill,Silver,2
64,20,Kjetil Andr Aamodt,M,22.0,176.0,85.0,Norway,NOR,1994 Winter,1994,Winter,Lillehammer,Alpine Skiing,Alpine Skiing Men's Super G,Bronze,1
67,20,Kjetil Andr Aamodt,M,22.0,176.0,85.0,Norway,NOR,1994 Winter,1994,Winter,Lillehammer,Alpine Skiing,Alpine Skiing Men's Combined,Silver,2
73,20,Kjetil Andr Aamodt,M,30.0,176.0,85.0,Norway,NOR,2002 Winter,2002,Winter,Salt Lake City,Alpine Skiing,Alpine Skiing Men's Super G,Gold,3
76,20,Kjetil Andr Aamodt,M,30.0,176.0,85.0,Norway,NOR,2002 Winter,2002,Winter,Salt Lake City,Alpine Skiing,Alpine Skiing Men's Combined,Gold,3
78,20,Kjetil Andr Aamodt,M,34.0,176.0,85.0,Norway,NOR,2006 Winter,2006,Winter,Torino,Alpine Skiing,Alpine Skiing Men's Super G,Gold,3
79,21,Ragnhild Margrethe Aamodt,F,27.0,163.0,NaN,Norway,NOR,2008 Summer,2008,Summer,Beijing,Handball,Handball Women's Handball,Gold,3
86,25,Alf Lied Aanning,M,24.0,NaN,NaN,Norway,NOR,1920 Summer,1920,Summer,Antwerpen,Gymnastics,"Gymnastics Men's Team All-Around, Free System",Silver,2
91,29,Willemien Aardenburg,F,22.0,NaN,NaN,Netherlands,NED,1988 Summer,1988,Summer,Seoul,Hockey,Hockey Women's Hockey,Bronze,1
92,30,Pepijn Aardewijn,M,26.0,189.0,72.0,Netherlands,NED,1996 Summer,1996,Summer,Atlanta,Rowing,Rowing Men's Lightweight Double Sculls,Silver,2
105,37,Ann Kristin Aarnes,F,23.0,182.0,64.0,Norway,NOR,1996 Summer,1996,Summer,Atlanta,Football,Football Women's Football,Bronze,1
106,38,Karl Jan Aas,M,20.0,NaN,NaN,Norway,NOR,1920 Summer,1920,Summer,Antwerpen,Gymnastics,"Gymnastics Men's Team All-Around, Free System",Silver,2
110,40,Roald Edgar Aas,M,23.0,NaN,NaN,Norway,NOR,1952 Winter,1952,Winter,Oslo,Speed Skating,"Speed Skating Men's 1,500 metres",Bronze,1
113,40,Roald Edgar Aas,M,31.0,NaN,NaN,Norway,NOR,1960 Winter,1960,Winter,Squaw Valley,Speed Skating,"Speed Skating Men's 1,500 metres",Gold,3
117,42,Thomas Valentin Aas,M,25.0,NaN,NaN,Taifun,NOR,1912 Summer,1912,Summer,Stockholm,Sailing,Sailing Mixed 8 metres,Gold,3
150,56,Ren Abadie,M,21.0,NaN,NaN,France,FRA,1956 Summer,1956,Summer,Melbourne,Cycling,"Cycling Men's Road Race, Team",Gold,3
158,62,Giovanni Abagnale,M,21.0,198.0,90.0,Italy,ITA,2016 Summer,2016,Summer,Rio de Janeiro,Rowing,Rowing Men's Coxless Pairs,Bronze,1
159,63,Jos Luis Abajo Gmez,M,30.0,194.0,87.0,Spain,ESP,2008 Summer,2008,Summer,Beijing,Fencing,"Fencing Men's epee, Individual",Bronze,1
161,65,Patimat Abakarova,F,21.0,165.0,49.0,Azerbaijan,AZE,2016 Summer,2016,Summer,Rio de Janeiro,Taekwondo,Taekwondo Women's Flyweight,Bronze,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270914,135481,"Jules Alexis ""Louis"" Zutter",M,30.0,NaN,NaN,Switzerland,SUI,1896 Summer,1896,Summer,Athina,Gymnastics,Gymnastics Men's Horse Vault,Silver,2
270915,135481,"Jules Alexis ""Louis"" Zutter",M,30.0,NaN,NaN,Switzerland,SUI,1896 Summer,1896,Summer,Athina,Gymnastics,Gymnastics Men's Parallel Bars,Silver,2
270917,135481,"Jules Alexis ""Louis"" Zutter",M,30.0,NaN,NaN,Switzerland,SUI,1896 Summer,1896,Summer,Athina,Gymnastics,Gymnastics Men's Pommelled Horse,Gold,3
270931,135486,Viktor Valeryevich Zuyev,M,21.0,188.0,91.0,Belarus,BLR,2004 Summer,2004,Summer,Athina,Boxing,Boxing Men's Heavyweight,Silver,2
270934,135488,Nataliya Vladimirovna Zuyeva,F,19.0,176.0,62.0,Russia,RUS,2008 Summer,2008,Summer,Beijing,Rhythmic Gymnastics,Rhythmic Gymnastics Women's Group,Gold,3
270939,135489,Anastasiya Valeryevna Zuyeva-Fesikova,F,22.0,182.0,71.0,Russia,RUS,2012 Summer,2012,Summer,London,Swimming,Swimming Women's 200 metres Backstroke,Silver,2
270946,135491,Marijan uej,M,22.0,186.0,93.0,Yugoslavia,YUG,1956 Summer,1956,Summer,Melbourne,Water Polo,Water Polo Men's Water Polo,Silver,2
270960,135498,Denis vegelj,M,20.0,NaN,NaN,Slovenia,SLO,1992 Summer,1992,Summer,Barcelona,Rowing,Rowing Men's Coxless Pairs,Bronze,1
270969,135501,Ellina Aleksandrovna Zvereva (Kisheyeva-),F,35.0,183.0,100.0,Belarus,BLR,1996 Summer,1996,Summer,Atlanta,Athletics,Athletics Women's Discus Throw,Bronze,1
270970,135501,Ellina Aleksandrovna Zvereva (Kisheyeva-),F,39.0,183.0,100.0,Belarus,BLR,2000 Summer,2000,Summer,Sydney,Athletics,Athletics Women's Discus Throw,Gold,3
270976,135502,"Nataliya Maratovna ""Natasha"" Zvereva",F,21.0,172.0,60.0,Unified Team,EUN,1992 Summer,1992,Summer,Barcelona,Tennis,Tennis Women's Doubles,Bronze,1
270981,135503,Zurab Zviadauri,M,23.0,182.0,90.0,Georgia,GEO,2004 Summer,2004,Summer,Athina,Judo,Judo Men's Middleweight,Gold,3
270982,135504,Viktor Oleksandrovych Zviahintsev,M,25.0,178.0,79.0,Soviet Union,URS,1976 Summer,1976,Summer,Montreal,Football,Football Men's Football,Bronze,1
270986,135508,Vera Igorevna Zvonaryova,F,23.0,172.0,59.0,Russia,RUS,2008 Summer,2008,Summer,Beijing,Tennis,Tennis Women's Singles,Bronze,1
271009,135520,Julia Zwehl,F,28.0,167.0,60.0,Germany,GER,2004 Summer,2004,Summer,Athina,Hockey,Hockey Women's Hockey,Gold,3
271010,135521,Anton Zwerina,M,23.0,NaN,66.0,Austria,AUT,1924 Summer,1924,Summer,Paris,Weightlifting,Weightlifting Men's Lightweight,Silver,2
271013,135522,"Klaas Erik ""Klaas-Erik"" Zwering",M,23.0,189.0,80.0,Netherlands,NED,2004 Summer,2004,Summer,Athina,Swimming,Swimming Men's 4 x 100 metres Freestyle Relay,Silver,2
271015,135523,"Ronald Ferdinand ""Ron"" Zwerver",M,25.0,200.0,93.0,Netherlands,NED,1992 Summer,1992,Summer,Barcelona,Volleyball,Volleyball Men's Volleyball,Silver,2
271016,135523,"Ronald Ferdinand ""Ron"" Zwerver",M,29.0,200.0,93.0,Netherlands,NED,1996 Summer,1996,Summer,Atlanta,Volleyball,Volleyball Men's Volleyball,Gold,3
271019,135525,Martin Zwicker,M,29.0,175.0,64.0,Germany,GER,2016 Summer,2016,Summer,Rio de Janeiro,Hockey,Hockey Men's Hockey,Bronze,1
271032,135535,Claudia Antoinette Zwiers,F,22.0,181.0,78.0,Netherlands,NED,1996 Summer,1996,Summer,Atlanta,Judo,Judo Women's Middleweight,Bronze,1
271046,135544,Krzysztof Zwoliski,M,21.0,175.0,70.0,Poland,POL,1980 Summer,1980,Summer,Moskva,Athletics,Athletics Men's 4 x 100 metres Relay,Silver,2
271048,135545,Henk Jan Zwolle,M,27.0,197.0,93.0,Netherlands,NED,1992 Summer,1992,Summer,Barcelona,Rowing,Rowing Men's Double Sculls,Bronze,1
271049,135545,Henk Jan Zwolle,M,31.0,197.0,93.0,Netherlands,NED,1996 Summer,1996,Summer,Atlanta,Rowing,Rowing Men's Coxed Eights,Gold,3
271076,135553,Galina Ivanovna Zybina (-Fyodorova),F,21.0,168.0,80.0,Soviet Union,URS,1952 Summer,1952,Summer,Helsinki,Athletics,Athletics Women's Shot Put,Gold,3
271078,135553,Galina Ivanovna Zybina (-Fyodorova),F,25.0,168.0,80.0,Soviet Union,URS,1956 Summer,1956,Summer,Melbourne,Athletics,Athletics Women's Shot Put,Silver,2
271080,135553,Galina Ivanovna Zybina (-Fyodorova),F,33.0,168.0,80.0,Soviet Union,URS,1964 Summer,1964,Summer,Tokyo,Athletics,Athletics Women's Shot Put,Bronze,1
271082,135554,Bogusaw Zych,M,28.0,182.0,82.0,Poland,POL,1980 Summer,1980,Summer,Moskva,Fencing,"Fencing Men's Foil, Team",Bronze,1
271102,135563,Olesya Nikolayevna Zykina,F,19.0,171.0,64.0,Russia,RUS,2000 Summer,2000,Summer,Sydney,Athletics,Athletics Women's 4 x 400 metres Relay,Bronze,1
271103,135563,Olesya Nikolayevna Zykina,F,23.0,171.0,64.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Athletics,Athletics Women's 4 x 400 metres Relay,Silver,2